### ISSUE TITLE
Bug: HASS.Agent doesn't run my Powershell command

### ISSUE THREAD

**Issue by ars4l4n** [hass-agent/HASS.Agent#112]
**Describe the bug**
I’m trying to run the following Powershell command via HASS.Agent:
`Invoke-Item "C:\Users\arsi\Desktop\Autohotkey Scripts\fertige\OBS Replaypuffer restarten.ahk"`
but said file doesn’t start. 

**To Reproduce**

HASS.Agent>Commands>New>Powershell
Then enter said command into the "Command or Script" box or enter the path to the .ps1 script containing this line there: `C:\Users\arsi\Desktop\test.ps1`
Then click Store Command>Store and Activate Commands.
Then run that action via a Home Assisstant script.
Since there is no AHK hotkey in the taskbar, that means the script isn't running

**Expected behavior**
`OBS Replaypuffer restarten.ahk` starting

**Misc info (please complete the following information):**
![winver_2024-07-03_17-32-20](https://github.com/hass-agent/HASS.Agent/assets/47932878/a26d0018-6804-4ece-989d-130b70a43723)

 - Windows' UI language: English
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent

**Additional context**
Launching the .ahk via a regular Windows Powershell window does work.

**Logs**
Logs after restarting HASS.Agent and running the Powershell Command as a quick action:
https://pastebin.com/SA81RvxB
I'm not seeing the name of the command in the log.

**Comment by amadeo-alex** [comment]
Hello, how are you invoking the command from Home Assistant's side?

**Comment by ars4l4n** [comment]
> Hello, how are you invoking the command from Home Assistant's side?

Eg. via Developer Tools>Services>Button: Press and then choosing my Powershell command as an entity.
Btw, I noticed it doesn't work with the monitor-off command anymore, either.

**Comment by amadeo-alex** [comment]
Hm, I'm running the bleeding edge test version and (although it should be same on 2.0.1):
- tested with "C:\Users\Amadeo\Desktop\łść!@#\script.ps1" - works fine (but I'm quite sure it worked with 2.0.1)
- Invoke-Item 'path to a mp3 file' - doesn't work
- creating new file "C:\Users\Amadeo\Desktop\łść!@#\playmp3.ps1" and putting "Invoke-Item 'path to a mp3 file'" - works fine (maybe a solution in your case?)

I'm not sure if the Invoke-Item ever worked on it's own (although it's executed properly nothing happens on the system.

Another topic is the other command not working for you - are none of the commands working or? Because then it might be another issue.

**Comment by ars4l4n** [comment]
Invoke-Item "C:\Users\arsi\Desktop\test.ps1" was the only one out of the 3 that did something. However, it only opened the script as a notepad file instead of running it. What now?

Ignore when I said the other command didn't work. It's working again.

**Comment by ars4l4n** [comment]
@amadeo-alex Did you see I edited my comment?

**Comment by amadeo-alex** [comment]
> Invoke-Item "C:\Users\arsi\Desktop\test.ps1" was the only one out of the 3 that did something. However, it only opened the script in Notepad instead of running it. To fix this, I thought of setting Powershell as the default application to run .ps1 files within Windows. I don't think that would do anything though since rightclicking a .ps1 script and selecting open with>Powershell doesn't execute the command either. I also updated to 2.1.0.-beta2 and tried all previous workarounds again with no success.
> 
> Another workaround I tried was executing a CustomExecutorCommand: `"C:\Users\arsi\Desktop\Autohotkey Scripts\fertige\OBS Replaypuffer restarten.ahk"` with `C:\Program Files\AutoHotkey\AutoHotkey.exe` set as the Custom Executor Binary under Configuration. It worked at first but now the script doesn't start anymore for some reason.
> 
> What now?
> 
> By the way, Ignore when I said the other command didn't work. It's working again.

If the first refers to the third bullet point from my message then it's not quite correct - "Invoke-item" needs to be only inside the ps1 file:
![VqYPyD](https://github.com/hass-agent/HASS.Agent/assets/68441479/408a35e7-ffd4-4896-b862-c0a6ae21d70f)

and the contents of the "playmp3.ps1" file:
`Invoke-Item 'X:\SomePath\The Prodigy -  Spitfire.mp3'`

**Comment by ars4l4n** [comment]
I even have the issue of nothing happening upon triggering the command when putting `invoke-item` in my .ps1 file instead of inside the HASS.Agent Command field.

**Comment by ars4l4n** [comment]
No.

**Comment by amadeo-alex** [comment]
Then there is another issue present I think - if the following example that I posted doesn't work https://github.com/hass-agent/HASS.Agent/issues/112#issuecomment-2211832370

**Comment by ars4l4n** [comment]
What's our next troubleshooting step?

**Comment by amadeo-alex** [comment]
I'll be honest that I'm not sure - the most basic example with mp3 file should work.
Could you please paste me the contents of "sensors.json" file? (it's in the config folder, open the log folder from HASS.Agent UI, navigate up one folder and then to "config")

**Comment by ars4l4n** [comment]
[sensors.json](https://github.com/user-attachments/files/16184489/sensors.json)

**Comment by ars4l4n** [comment]
I solved the issue. Running scripts was disabled on my system, as per default for Windows-Clients and I had to set an execution policy to enable them.
I did that by running PowerShell as an administrator and using `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`.

**Comment by amadeo-alex** [comment]
Thank you for the info! We should probably add it to the docs, @DrR0X-glitch what do you think?

**Comment by DrR0X-glitch** [comment]
> Thank you for the info! We should probably add it to the docs, @DrR0X-glitch what do you think?

Yeah might do it in my next PR, although the first troubleshooting step we suggest in this case is if the script can be run from a normal terminal, which would've failed if execution policy is wrong.
