### ISSUE TITLE
Bug: Lost Notifications if PC is not active?

### ISSUE THREAD

**Issue by TarheelGrad1998** [hass-agent/HASS.Agent#114]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
Notifications sent to my PC via HASS.Agent work fine when it is awake/active.  However, I frequently miss notifications if they are sent during a period when my computer is offline.  I assumed they should get queued on MQTT and display the next time my computer wakes?  That isn't happening for me, and I thought it was my configuration yet I cannot find anything.

**To Reproduce**
1. Put PC to Sleep
2. Send Notification to HASS.Agent from HA

**Expected behavior**
Notifications sent while PC is offline are shown when PC wakes and HASS.Agent resumes.

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/hass-agent/HASS.Agent/assets/47931551/bb82f6e7-7cae-47c6-823e-b89500568e09)

 - Windows' UI language: English
 - HASS.Agent version: 2.1.0-beta2

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
What you're experiencing is the expected behaviour, if the device is not online it will not receive the messages.
Even if they'd be sent to MQTT broker with retain flag:
- there is no way to tell when they were sent by Home Assistant/other source
- only one message can be retained by the MQTT broker (so even ignoring above doesn't solve "the issue")

**Comment by TarheelGrad1998** [comment]
Ah, bummer.  I'm using it to send camera notifications to my PC and mostly it works great.  Occasionally, we get a package late.  I'd still like to know if someone entered the yard while my PC (and/or I) am asleep.  

Thanks for the clarification.
