### ISSUE TITLE
Feature:  Command to Open Web URL  Set to the  Tray Icon

### ISSUE THREAD

**Issue by rxritalin** [hass-agent/HASS.Agent#116]
**Is your feature request related to a problem? Please describe.**
The issue is that I am trying to create a seamless automation for opening a touch panel display when a user nears the device. 
Since the tray icon webview has the option to keep the page loaded in the background, this webview loads instantly. 
Webview windows setup as commands only store cookies and as such still need to load the page each time. 

**Describe the solution you'd like**
There are two options to resolve this as I can see. 
1. Give the ability to launch the tray icon webview shortcut via a command. 
2. Give every webview command you create the same option to stay loaded in the background. 

**Describe alternatives you've considered**
I've looked for a way to launch the tray icon webview via powershell or command prompt, but I'm coming up short. 
Full browser windows are way too heavy as this is all running from a little N95 cpu. 

The page I am loading has a good deal of Card_Mod CSS editing, and as I am sure you are aware, some of the CSS edits take a second to load. This can lead to the page being loaded in the current webview command to look funky before finally loading all the way up. 
This is for a dedicated touch screen that controls my living room stereo through Music Assistant. Its a fullscreen card and as such is a little on the heavy side, with image art, background image art running through CSS filters, etc. 
I was very excited to find that someone had taken up the HASS.Agent mantle and had hoped someone had already requested somethign similar, but didnt see  a request for it, so here I am.

**Comment by amadeo-alex** [comment]
Thanks for the suggestion - overall looks doable but I need to do some test here and there to be sure.
If possible will *maybe*  it'll make it's way to 2.1.0-beta3 and the full 2.1.0.

**Comment by amadeo-alex** [comment]
Implemented, will be part of beta3 :)

**Comment by rxritalin** [comment]
> Implemented, will be part of beta3 :)

Sweet!!! Can't wait to test it out. 
Thank you for working on this request.
