### ISSUE TITLE
Bug: Playing Automation with a Quick Action doesn't work.

### ISSUE THREAD

**Issue by SerinitySW** [hass-agent/HASS.Agent#117]
**Describe the bug**
Quick Actions don't seem to be able to play/run an automation manually. It has no problem turning them on and off, but you can't make an automation run.

**To Reproduce**
1. Open HASS.Agent Quick Actions Config
2. Add New
3. Automation > Select entity > Set Desired Action to "Play"
4. Either run with a hotkey or manually

**Expected behavior**
Simply running the automation when you execute the quick action would be wonderful :)

**Screenshot**
![image](https://github.com/user-attachments/assets/f4e0a61d-bcdc-4e48-9385-0523b2e9901a)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/user-attachments/assets/45e8a58b-3dbb-4e76-8fa4-9fa6c18913b0)

 - Windows' UI language: English US
 - HASS.Agent version: Latest at the time of writing (2.0.1)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
![image](https://github.com/user-attachments/assets/937db9a4-0b74-4f13-8b06-4ed8c728b4d4)

**Logs**
[[2024-07-11] HASS.Agent_20240711.log](https://github.com/user-attachments/files/16183623/2024-07-11.HASS.Agent_20240711.log)

**Comment by SerinitySW** [comment]
As a temporary workaround, I've created a toggle helper and then set it to true when running the quick action. That then triggers the automation, which turns the toggle back off when it is done. Requested button helper support in #118.

**Comment by amadeo-alex** [comment]
Ok, tested, and replicated the issue. Looks like it's something I'd need to update HADotNet library - doable as I've seen the "/api/services/automation/trigger" REST API endpoint but I can't put exact date on the implementation. Will keep you posted.

**Comment by amadeo-alex** [comment]
Implemented, will be part of 2.1.0-beta3 and full 2.1.0 releases.
