### ISSUE TITLE
Feature: Button Helper support for quick action

### ISSUE THREAD

**Issue by SerinitySW** [hass-agent/HASS.Agent#118]
**Is your feature request related to a problem? Please describe.**
It is a temporary workaround for [#117](https://github.com/hass-agent/HASS.Agent/issues/117).

**Describe the solution you'd like**
Be able to "toggle" a button. Currently, button helpers don't show up in the input boolean list.

**Describe alternatives you've considered**
At the moment you have to workaround the workaround with a toggle that an automation turns back off (effectively making a button).

**Additional context**
N/A

**Comment by amadeo-alex** [comment]
Hmm, correct me if I'm wrong please but Home Assistant doesn't have "toggle buttons" per se but rather switches are used for this?
I think I need more explanation to fully understand this request please.

**Comment by SerinitySW** [comment]
Ah, it seems I misremembered that Homeassistant uses the word "Press" for buttons instead of "Toggle". It'd be nice to be able to push buttons via HASS.Agent.

**Comment by amadeo-alex** [comment]
Implemented, will be part of 2.1.0-beta3 and full 2.1.0 releases.
