### ISSUE TITLE
Bug: LastActive sensor sometimes doesn't report its value to HA

### ISSUE THREAD

**Issue by ars4l4n** [hass-agent/HASS.Agent#119]
**Describe the bug**
HASS.Agent's LastActive sensor is set to report every 300s and it usually does that but I just noticed it skipped one of its timings and reported after 600s instead.

**To Reproduce**
1) Create a LastActive sensor that updates every 300s in HASS.Agent.
2) Create an automation based on said sensor and once it behaves weirdly, check HA's Logbook page for times when the state wasn't reported.

**Expected behavior**
LastActive being reported every 300s.

**Screenshots**
![chrome_2024-07-12_17-10-41](https://github.com/user-attachments/assets/fcd5cb02-ceb9-44a5-a514-6770b6f84f72)

**Misc info (please complete the following information):**
![image](https://github.com/user-attachments/assets/b2c36215-7c7e-429d-af51-91fed723d68b)
- Windows' UI language: English
- HASS.Agent version: 2.1.0-beta2

Please check what's applicable (multiple answers possible):
 - [x] Installed via installer
 - [x] Problem occurs in HASS.Agent

**Logs**
The HASS.Agents logs (non-extended) don't contain any entries for the time the issue occured.

**Comment by amadeo-alex** [comment]
HASS.Agent won't send the value to Home Assistant unless it changed from the one that was previously sent - is it possible that the computer didn't receive any input throughout those 600s?

**Comment by ars4l4n** [comment]
It probably didn't since I was watching a netflix show. I was assuming the sensor saw playing video or audio as using the PC as well. Is there a way to use that on top of that as a sensor?

**Comment by amadeo-alex** [comment]
One option is the peak volume sensor but if the application/browser properly integrates with Windows you could use the media player status to check if something is playing.
