### ISSUE TITLE
Sensor Update interval is not respected:

### ISSUE THREAD

**Issue by AJolly** [hass-agent/HASS.Agent#121]
I've got a custom sensor set, with a long timeout, yet I can see HASS agent running the  powershell query every few seconds.

`    "Type": "PowershellSensor",
    "Id": "23e28934-05c7-4fb8-9840-0d52f5dfd83f",
    "Name": "powerplan",
    "UpdateInterval": 240,
    "Query": "Get-WmiObject -Namespace root\\cimv2\\power -Class Win32_PowerPlan | Where-Object { $_.IsActive -eq $true } | Select-Object ElementName",
    "Scope": null,
    "WindowName": "",
    "Category": "",
    "Counter": "",
    "Instance": "",
    "EntityName": "powerplan",
    "IgnoreAvailability": false,
    "ApplyRounding": false,
    "Round": null
  },`

**Comment by amadeo-alex** [comment]
Hello, please update the issue to match the required template, thank you.
