### ISSUE TITLE
Bug: Hass.Agent application crashes when using sensors

### ISSUE THREAD

**Issue by Dutchbear22** [hass-agent/HASS.Agent#14]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
When I use the HASS.Agent application on Windows 11 then it immediately crashes after loading all the features. I am using the following sensors:

CPU_Load
MemoryUsage
GPULoad

**To Reproduce**
1. Open HASS.Agent.exe
2. Wait for the application to load all the features (Home assistant API, MQTT etc)
3. The application crashes after loading the features.

**Expected behavior**
The application crashes when all the features are loaded. 

**Screenshots**
N/A

**Misc info (please complete the following information):**
 - Windows 11 23H2
 - Windows' UI language: English (United States)
 - HASS.Agent version: It both happens in version 2022.14.0 and 2023.11.1-ubeta
 - My specs are: AMD Radeon RX 7900 XTX, AMD Ryzen 7 5800X, and 32 GB DDR4. 

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
[[2023-11-15] HASS.Agent_20231115.log](https://github.com/amadeo-alex/HASS.Agent/files/13367775/2023-11-15.HASS.Agent_20231115.log)

**Comment by amadeo-alex** [comment]
As per our discord discussions, I've checked the code and each of the commands/sensors publish calls are wrapped in try/catch block. I might be missing something here but the fact that application is closing just like that without any error in the logs in at least concerning.
I'd like to ask you to check the Windows event viewer once the application crashes but I know you're currently testing something else, I'll grab you on discord with the details :)

**Comment by amadeo-alex** [comment]
Might be a possible issue with our usage to LibreHardwareMonitor.
Buthchbear22 is able to use the stock LHM GUI app without crash whilst there is possible crash point in the sensor:
![mgFba6](https://github.com/amadeo-alex/HASS.Agent/assets/68441479/70545c40-ccf5-45ba-bc4c-3cb727af949f)

**Comment by amadeo-alex** [comment]
Fixed in https://github.com/hass-agent/HASS.Agent/releases/tag/2.0.0
