### ISSUE TITLE
Bug: Sending Multiple Keys seemingly non-functional

### ISSUE THREAD

**Issue by HexagonIsTheBestagon** [hass-agent/HASS.Agent#147]
----

**Describe the bug**

I want to send the keystroke CTRL + ALT + F11 to my PC via multiplekeys in the command section. 

I have tried these Keycodes:

[^%F11] -> Does nothing
[^%[{F11}]] -> Only F11
[^] [%] [F11] -> Sends them one after the other
[^] [%] [{F11}] -> Only F11 again

None have worked, and I am out of ideas. 
Maybe I just don't understand the syntax? 

**Expected behavior**

Sending the Keystroke CTRL + ALT + F11

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
Hello,

Please try:
```
[^%{F11}]
```
Reference: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys?view=windowsdesktop-8.0
