### ISSUE TITLE
Bug: Remote desktop connection causes HASS.agent to crashes

### ISSUE THREAD

**Issue by danishru** [hass-agent/HASS.Agent#149]
**Describe the bug**
When connecting remotely using the Remote Desktop Connection program to a running session with HASS.Agent running, HASS.Agent crashes.

**To Reproduce**
1. Run HASS.Agent locally on the user's computer.
2. Connect via RDP from another computer to the same or another user on this computer..
3. HASS.Agent will crash on the user it was run on.
4. See error.

**Expected behavior**
HASS.Agent should not crash

**Misc info (please complete the following information):**
 - Windows build: Windows 11 Pro 23H2 build 22631.4037
 - Windows' UI language: Russian
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
[[2024-08-29][E] HASS.Agent_20240829.log](https://github.com/user-attachments/files/16800756/2024-08-29.E.HASS.Agent_20240829.log)

**Comment by amadeo-alex** [comment]
Hello, please try one of the beta releases as some of the virtual desktop management has changes and it might be causing the crash - https://github.com/hass-agent/HASS.Agent/releases

**Comment by danishru** [comment]
> Hello, please try one of the beta releases as some of the virtual desktop management has changes and it might be causing the crash - https://github.com/hass-agent/HASS.Agent/releases

Hello, after updating to version 2.1.0 the problem is no longer observed. Great job, thank
