### ISSUE TITLE
Bug: With and RDP(Remote Desktop) application in the foreground playback controls do not work

### ISSUE THREAD

**Issue by inphinitizeit** [hass-agent/HASS.Agent#181]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
With an RDP (Remote Desktop) window in the foreground media playback controls do not function

**To Reproduce**
1. Play audio on the computer running hass.agent
2. Put an RDP window in foreground
3. Execute a play/pause command from home assistant

**Expected behavior**
Music pauses on the computer.

** Actual behavior **
The RDP window swallows the key presses and no pause is made on the host computer.

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/user-attachments/assets/d64e59e8-e028-4a98-9488-a8e2d3c98f0d)

 - Windows' UI language: 
 - HASS.Agent version: 2.1.0

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
I'm afraid that's the "current expected behaviour" - HASS.Agent sends the media keys via [SendInput](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput). If RDP is in the foreground is at the top it steals all key/keyboard events.

I'll see if we could use the media player API to do the same but we'd also need to think about players/applications that do not use windows media player api and just listen for keyboard events to support "media keys".

**Comment by amadeo-alex** [comment]
I just had an opportunity to use a HyperV machine via RDP (enhanced session). All my keyboard media keys worked as you've explained - when RDP window was active it received the input.

You can try is to use the integration/media player pause/play controls as they work differently as I've mentioned before but the player must support the windows media player api.
I'll close this for now but please feel free to comment if you'll have other ideas.

**Comment by inphinitizeit** [comment]
Makes sense, I'll look into some other possibilities as well. I had read somewhere it might be possible to target the desktop window instead of the foreground window when calling sendinput but I haven't had time to follow up yet.
