### ISSUE TITLE
Bug: microphoneprocess does not clear active attributes

### ISSUE THREAD

**Issue by DanielTerletzkiy** [hass-agent/HASS.Agent#195]
**Describe the bug**
before using this fork, i was using the original HASS.Agent
i once played Content Warning and was using Discord at the same time
my PC crashed in the middle of the session and ever since that happened these two programs have been stuck as "ON" in the attributes.

they cannot be cleared, and i *thought* that clearing all HASS.Agent files from the %appdata% will fix it, but i think that it was not the right directory as the issue persisted

when i use anything other than discord or content warning, like zoom, it will be "on" and then go away as it should

**To Reproduce**
1. Use old Hass.Agent
2. Crash PC with Discord and Content Warning listed in microphoneprocess
3. Have them persist for 6 months

**Expected behavior**
both microphoneprocess should be clearable
or find the file/location where this variable is cached so i could clear it manually

**Screenshots**
![image](https://github.com/user-attachments/assets/e3f92976-2b6c-4d4d-a73f-5acdcd6553f5)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/user-attachments/assets/1d64e5ee-89ab-428d-9ab5-939a8fce8632)
 - HASS.Agent version: still persists on 2.1.1-beta2 (but this has happened on a much older version)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
That's interesting, I think we had this discussion on discord somewhere :D
So, do you by any chance have MQTTExplorer installed?

**Comment by DanielTerletzkiy** [comment]
i do have it installed!
i don't know what you want to see so i am just going to dump the things related to the sensor:

 `homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess`
 null
 
 `homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess/config`
```json
 {
  "state_class": "measurement",
  "icon": "mdi:microphone",
  "json_attributes_topic": "homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess/attributes",
  "unique_id": "0fbc9587-22ea-45f5-89a5-8a2138a86b18",
  "object_id": "DANIEL-PC_microphoneprocess",
  "availability_topic": "homeassistant/sensor/DANIEL-PC/availability",
  "device": {
    "identifiers": "hass.agent-DANIEL-PC",
    "manufacturer": "HASS.Agent Team",
    "model": "Microsoft Windows NT 10.0.26100.0",
    "name": "DANIEL-PC",
    "sw_version": "2.1.1-beta2"
  },
  "entityname": "DANIEL-PC_microphoneprocess",
  "name": "DANIEL-PC_microphoneprocess",
  "state_topic": "homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess/state"
}
```

`homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess/state`
2

`homeassistant/sensor/DANIEL-PC/DANIEL-PC_microphoneprocess/attributes`
```
{
  "Content Warning": "on",
  "Discord": "on"
}
```

please comment if you need more information @amadeo-alex :)

**Comment by amadeo-alex** [comment]
Ok, I assume discord and "content" warning were not active while testing :D
Looks like this might be the same issue as https://discord.com/channels/1173033284519862392/1235336244339409067

If you don't have access to discord, for some reason, windows sometimes borks and leaves registry entries for the apps that are no longer using microphone:
![GC6YPU](https://github.com/user-attachments/assets/64bee114-1134-4844-aa28-6a8f0454c2b7)

Easiest fix is that you open regedit, navigate to the path visible on the screenshot and then remove the entries + reboot the PC.
Are you accustomed to working with stuff like regedit or would you like some help :D?

**Comment by DanielTerletzkiy** [comment]
@amadeo-alex thank you so much! it got fixed right away!

i looked into the entries for Content Warning and the various Discord ones and found exactly two of them that were out of place.
both entries had the `LastUsedTimeStop `value set to 0x000.. so i just copied the start value into the end value :)

6+ months of broken microphone sensor issues now gone!
