### ISSUE TITLE
Bug: MicrophoneProcess Showing number, not service name

### ISSUE THREAD

**Issue by 1liminal1** [hass-agent/HASS.Agent#201]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
So instead of showing the process, I just get a number. 

![image](https://github.com/user-attachments/assets/0a0bf052-8539-4163-978a-4b72d8152787)

**To Reproduce**
Run the microphone and then look in the sensors config

**Expected behavior**
There used to be the process name in the last known value

**Screenshots**
Above 

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 
![image](https://github.com/user-attachments/assets/ed040814-ad46-4072-ae08-0d3617a94e0a)

 - Windows' UI language: 
 ENG
 - HASS.Agent version: 
 
![image](https://github.com/user-attachments/assets/7b7aab0d-2b82-44a2-a377-6ed47c36bc4b)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`.

**Comment by amadeo-alex** [comment]
Hello,
Have you checked the attributes? The specific process names are there, example:
![QiwO0U](https://github.com/user-attachments/assets/d6381e85-5a11-415d-b73a-b3a9a8d07f13)
