### ISSUE TITLE
Bug: media player not visible in HA

### ISSUE THREAD

**Issue by moskovskiy82** [hass-agent/HASS.Agent#36]
Documentation states that the media player should be discovered via MQTT (although the link to the docs is broken currently).
I have successfully set the sensors/commands and they all got auto discovered but the media player just doesn't show up 

![image](https://github.com/hass-agent/HASS.Agent/assets/15857592/b16611c2-49fe-4d99-b6b2-ed3981b87b60)

![image](https://github.com/hass-agent/HASS.Agent/assets/15857592/d0717e6c-5093-4271-8774-fee7606f349b)

**Comment by danishru** [comment]
For media center to work and auto-detect, you need to install custom integration from HACS https://github.com/LAB02-Research/HASS.Agent-Integration.

**Comment by amadeo-alex** [comment]
Is this still an issue after installing the integration?

**Comment by markusmoormann** [comment]
Are there any changes regarding this Ticket? I lost my media player some Days ago. Updated to this fork, removed Hass Integration multiple Times, but the media player entity doesnt Show up. Any Ideas? 
![Screenshot_20240514_201541_Home Assistant](https://github.com/hass-agent/HASS.Agent/assets/2950375/c89ddc89-d3a7-491d-abc7-3f7c08d3c82d)

**Comment by amadeo-alex** [comment]
Not from our side no.
Is the integration that you have installed a forked one (https://github.com/hass-agent/HASS.Agent-Integration) or the original one? There have been changes in HA 2024.5.X that prevent the old one from working.

**Comment by markusmoormann** [comment]
I installed this fork after the entity went unavailable. In the meantime the entity exists again but is still unavailable. 
![image](https://github.com/hass-agent/HASS.Agent/assets/2950375/df9b8562-0168-4d94-8d27-265492036cbd)

I'runing hass agent on a macbook running Windows 10 using apple bootcamp-assistant

![image](https://github.com/hass-agent/HASS.Agent/assets/2950375/fc88438e-428f-413c-bd4b-3e3b60fa8d11)
any advice what I could try?

**Comment by markusmoormann** [comment]
well..yesterday i looked at the init.py of the integration and realized it also uses mqqt. i was already wondering why my device was called DESKTOP... instead of KUECHE-MACBOOK and checked the mqtt broker with mqttexplorer and found more than device under the hass.agent Topic with the DESKTOP... Device beeing the first. I cleared all the topics and voila the correct device showed up and the Media Player works like before. isnthis supposed to Happen?

**Comment by amadeo-alex** [comment]
Not quite, the old messages staying there is a bug that was/will be fixed witb 2.1.0.

**Comment by kuligs2** [comment]
can someone confirm? im still having problems with media player not showing up in the HA for the PC. Using the latest HA and HACS agent integration (3 months ago).

I have tried many things, rebood, delete/add again, as per the unmaintained repo. 

How to add the media player?

**Comment by amadeo-alex** [comment]
> can someone confirm? im still having problems with media player not showing up in the HA for the PC. Using the latest HA and HACS agent integration (3 months ago).
> 
> I have tried many things, rebood, delete/add again, as per the unmaintained repo.
> 
> How to add the media player?

Did you follow the installation instructions?
https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation

**Comment by kuligs2** [comment]
> > can someone confirm? im still having problems with media player not showing up in the HA for the PC. Using the latest HA and HACS agent integration (3 months ago).
> > I have tried many things, rebood, delete/add again, as per the unmaintained repo.
> > How to add the media player?
> 
> Did you follow the installation instructions? https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation

HACS store already had this integration, and it complained to me when o was adding it as a custom integration. I went with the one that was on the sotre. Is that not the correct one? it says last update 3months ago

**Comment by nelson-tbone** [comment]
Hi, I don't know if it helps, but trying to add via Local API gives me this:

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 8:36:53 PM (2 occurrences)
Last logged: 8:37:03 PM

Error setting up entry bone7 for hass_agent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hass_agent/__init__.py", line 135, in async_setup_entry
    _logger.debug("setting up device from config entry: %s [%s]", entry.data["device"]["name"], entry.unique_id)
                                                                  ~~~~~~~~~~^^^^^^^^^^
KeyError: 'device'

**Comment by kuligs2** [comment]
the local api fails for me too, it says the port already in use.. i use all default settings..

**Comment by sriharshaguthikonda** [comment]
it is sitll an issue. idk what is going on. ! I thought home assistant is a solution to many problems. but it feels like it is a major source of problmes in life!

**Comment by kuligs2** [comment]
> it is sitll an issue. idk what is going on. ! I thought home assistant is a solution to many problems. but it feels like it is a major source of problmes in life!
> 
> installed the older version of Hass agent and still the same issue. installed the beta fork and still the same issue.

sorry, but i remember, i didnt follow the steps.. i installed the agent from the home assistant store or whats its called, but it was broken, i had to add this repository manually to install the working agent.. it was working and still is.. sorry for the delay

**Comment by amadeo-alex** [comment]
As mentioned here and in other issues/threads, the forked version of HASS.Agent (this one on "hass-agent" origanization) and currently even the original version **requires the forked integration to function (original version of the integration availably by default on HACS will not function)** https://github.com/hass-agent/HASS.Agent-Integration?tab=readme-ov-file#installation due to the Home Assistant changes and requirements.

I'm going to close this one as it doesn't even relate to HASS.Agent itself but rather the integration https://github.com/hass-agent/HASS.Agent-Integration.
Please feel free to open other issue here or in the integration repository if you've followed the installation steps and are still facing issues.
