### ISSUE TITLE
Feature: windows11

### ISSUE THREAD

**Issue by tennet** [hass-agent/HASS.Agent#44]
Hi thanks for your work, I'm trying to install the agent on Windows 11 there are problems, do you have any idea of an update for this? I would also like to take this opportunity to raise a point about the fact that in many installations (Windows) users are no longer using the administrator account but users with limited permissions.

**Comment by amadeo-alex** [comment]
Hello, if possible, please update the request to match the enhancement template.

What issues exactly are you facing on Windows 11?
 
> I would also like to take this opportunity to raise a point about the fact that in many installations (Windows) users are no longer using the administrator account but users with limited permissions.
For now unfortunately this can't be supported.

**Comment by sirmeili** [comment]
I'll just note I've been running this on Windows11 without problems since i first installed it probably a year ago (starting with the original project and then moving to this one).
