### ISSUE TITLE
Bug: MicrophoneProcessSensor description not accurate

### ISSUE THREAD

**Issue by Gvolten** [hass-agent/HASS.Agent#49]
**Describe the bug**
The `MicrophoneProcessSensor` does not report the process name as stated in the description, but rather the number of processes using the microphone at the current time. While this information is useful, you cannot create automations specific for certain processes.

**To Reproduce**
1. Create a new `MicrophoneProcessSensor`
2. Start processes using the microphone
3. Observe the `Last Known Value`

**Expected behavior**
The sensor should report the process names separated by some delimiter like `;`. For example: `Discord;obs`. To keep the functionality of reporting the number of processes, I would introduce a new sensor type.

**Misc info (please complete the following information):**
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):
 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by amadeo-alex** [comment]
Hello,

The applications that use microphone can be found in the attributes of the sensor - if that's what you're looking to find:
![wztw2g](https://github.com/hass-agent/HASS.Agent/assets/68441479/87b7fda4-ed7b-4a81-a07e-d9a748de3108)

**Comment by Gvolten** [comment]
Thank you, that is correct. But I still think that the description of that sensor should be updated as it is not accurate enough:
> Provides the name of the process that's currently using the microphone.
> Note: if used in the satellite service, it won't detect userspace applications.

**Comment by amadeo-alex** [comment]
Done with https://github.com/hass-agent/HASS.Agent/pull/57
