### ISSUE TITLE
Bug: PowershellSensor (Satellite) reports "Unknown"

### ISSUE THREAD

**Issue by EpicLPer** [hass-agent/HASS.Agent#52]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
Using the PowershellSensor and trying to output a log file to it shows up as "Unknown" in Home Assistant even tho the test button outputs the text just fine. I'm using `get-content E:\SteamCMD\logs\output.txt` as the command.

**To Reproduce**
1. Create a PowershellSensor
2. Enter `get-content E:\path\to\log\file\output.txt`
3. Check Home Assistant

**Expected behavior**
It should store the log file as a text in Home Assistant.

**Screenshots**
\-

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Server 2022 21H2
 - Windows' UI language: English
 - HASS.Agent version: 2.0.2beta2 (also happened on latest official version)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [X] Problem occurs in Satellite Service

**Additional context**
This has also already occurred in the original latest release of HASS.Agent.

**Logs**
No errors are being reported in either the satellite log nor normal log.

**Comment by EpicLPer** [comment]
Also tried the normal "local sensor" one and it produces the same result.

**Comment by EpicLPer** [comment]
After a few more tries to store the sensors I occasionally get the following error in either the satellite or the normal log:

```
2024-02-29 17:13:23.125 +01:00 [FTL] [SENSORSMANAGER] Error while publishing: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at HASS.Agent.Sensors.SensorsManager.Process() in D:\a\HASS.Agent\HASS.Agent\src\HASS.Agent\HASS.Agent\Sensors\SensorsManager.cs:line 133
2024-02-29 17:13:24.227 +01:00 [INF] [SENSORS] Modified single-value sensor: powershellsensor-test
2024-02-29 17:13:24.227 +01:00 [INF] [SETTINGS_SENSORS] Stored 1 entities
```

**Comment by amadeo-alex** [comment]
Hmm, I don't seem to be able to reproduce this:
![naK3AJ](https://github.com/hass-agent/HASS.Agent/assets/68441479/b61ebbee-c31f-4862-b8d1-a88c1dd307eb)
![obraz](https://github.com/hass-agent/HASS.Agent/assets/68441479/fba971bc-9292-4278-9f3d-cffe25471ad1)

Could you please check the Home Assistant logs? I'm asking because HA has a limit of payload it can handle - 255 characters - is it possible the log file is bigger than this?

**Comment by EpicLPer** [comment]
Aw damn... yes that was the issue...
I tried sending a log file over which was about 1KB big, course it's too big then.

Maybe this would be a good mention in the help-text to the right of the sensor for such scenarios 😅

**Comment by amadeo-alex** [comment]
Done - https://github.com/hass-agent/HASS.Agent/pull/58 :)

**Comment by EpicLPer** [comment]
Awesome, thanks!
