### ISSUE TITLE
Bug: Default Hotkey "Ctrl, Alt + Q" makes it impossible to type "@" on German keyboards

### ISSUE THREAD

**Issue by EpicLPer** [hass-agent/HASS.Agent#62]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
For the past days I've been wondering why I can't type the "@" symbol on my keyboard anymore. After digging around and realizing that the only app I've installed lately was HASS.Agent I found that the default hotkey of "Ctrl, Alt + Q" is resulting in this. The combination or "Alt Gr + Q" is usually reserved for @ on that layout. Disabling the hotkey inside HASS.Agent makes @ work again just fine.

**To Reproduce**
1. Have a German keyboard
2. Install HASS.Agent
3. The hotkey is by default enabled, so the bug should be reproducible at this point already

**Expected behavior**
"@" symbol should still work on German keyboards

**Screenshots**
\-

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Windows 11 23H2
 - Windows' UI language: English (German Keyboard)
 - HASS.Agent version: 2.1.0-beta1

**Please check what's applicable (multiple answers possible):**
 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
\-

**Logs**
\-

**Comment by amadeo-alex** [comment]
While I don't think that having both the hotkey and "@" working at the same time, I think we can add a logic that will alter the default hotkey if german keyboard layout is detected.
Any "german safe" hotkey combinations that you can suggest?

**Comment by EpicLPer** [comment]
From my tests "AltGr + H" should fit well :)
Else, potential different solution: Detect the layout > If it's German warn the user and ask him to make a new shortcut

**Comment by amadeo-alex** [comment]
Now I'm surprised, there is a check for "input language" being German in the code already :D
Did you by any chance receive that during the initial onboarding/configuration after installation?
Should be something like:
```
Your input language '{0}' is known to collide with the default CTRL-ALT-Q hotkey. Please set your own.
```
I'll also check if there is difference between C# input language and keyboard layout - maybe this is what we're missing.

**Comment by amadeo-alex** [comment]
@EpicLPer could you please execute following in powershell and provide me with output?
```
Get-WinUserLanguageList
```
It should respond back with something like this:
![GRAa5A](https://github.com/hass-agent/HASS.Agent/assets/68441479/453f38f9-c32b-4a09-a351-3b345e6f9190)

**Comment by EpicLPer** [comment]
Hi, sorry for the late reply.
The output is as follows:

```
LanguageTag     : de-AT
Autonym         : Deutsch (Österreich)
EnglishName     : German
LocalizedName   : German (Austria)
ScriptName      : Latin
InputMethodTips : {0C07:00000407}
Spellchecking   : True
Handwriting     : False

LanguageTag     : en-AT
Autonym         : English (Austria)
EnglishName     : English
LocalizedName   : English (Austria)
ScriptName      : Latin
InputMethodTips : {2000:00000407}
Spellchecking   : True
Handwriting     : False
```

**Comment by amadeo-alex** [comment]
Reopened until 2.1.0-beta2 is released for clarity sake.

**Comment by erd82** [comment]
Having exactly the same problem, that I cannot type email addresses (at-key) anymore once HASS Agent is running. So the application cannot run constantly in the background.

**Comment by amadeo-alex** [comment]
> Having exactly the same problem, that I cannot type email addresses (at-key) anymore once HASS Agent is running. So the application cannot run constantly in the background.
> 
> ![image](https://private-user-images.githubusercontent.com/63564291/331362493-b01a8b51-1980-413e-8cae-99dea0ef7053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzMzNzgsIm5iZiI6MTcxNTkzMzA3OCwicGF0aCI6Ii82MzU2NDI5MS8zMzEzNjI0OTMtYjAxYThiNTEtMTk4MC00MTNlLThjYWUtOTlkZWEwZWY3MDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA4MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZTA3NWYwNDAyYWRkOTRlYTkwYTRkY2MyZjM0ZjQ3YzNhZWY4M2IwZDdjZTNhMDNiNTEwM2ExODFlZDdlZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hvlbb2eawuYf6Q58pOG-czJbQD0ALjnoP3YmjFU1Dv4)

To fix that for now, please modify the hotkey shortcut to something else like Alt+H.
Next version fo HASS.Agent will warn about this during onboarding.
