### ISSUE TITLE
Bug: Memory Leak (audio library)

### ISSUE THREAD

**Issue by sreknob** [hass-agent/HASS.Agent#64]
----

**Describe the bug**
Things on my PC were feeling sluggish, fire up task manager and yikes - hass.agent using 3.5GB memory and 10% CPU. Yikes!

![image](https://github.com/hass-agent/HASS.Agent/assets/6324507/4e5d6906-3aa1-4ff8-ac75-e091e0196e98)

**To Reproduce**
Uncertain

**Expected behavior**
Reasonable resource usage 😄 

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): Win 10 22H2 19045.4170
 - Windows' UI language: English
 - HASS.Agent version: 2.1.0-beta1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
I took a memory dump of the process to share privately, if desired. Agent unable to restart itself, needed to be force killed.

**Logs**
Attached, in all their glory.
[[2024-03-11] HASS.Agent_20240312.log](https://github.com/hass-agent/HASS.Agent/files/14667607/2024-03-11.HASS.Agent_20240312.log)
[[2024-03-11] HASS.Agent_20240311.log](https://github.com/hass-agent/HASS.Agent/files/14667608/2024-03-11.HASS.Agent_20240311.log)
[[2024-03-09] HASS.Agent_20240311.log](https://github.com/hass-agent/HASS.Agent/files/14667609/2024-03-09.HASS.Agent_20240311.log)
[[2024-03-09] HASS.Agent_20240310.log](https://github.com/hass-agent/HASS.Agent/files/14667610/2024-03-09.HASS.Agent_20240310.log)
[[2024-03-09] HASS.Agent_20240309.log](https://github.com/hass-agent/HASS.Agent/files/14667611/2024-03-09.HASS.Agent_20240309.log)
[[2024-03-08] HASS.Agent_20240309.log](https://github.com/hass-agent/HASS.Agent/files/14667612/2024-03-08.HASS.Agent_20240309.log)
[[2024-03-08] HASS.Agent_20240308.log](https://github.com/hass-agent/HASS.Agent/files/14667613/2024-03-08.HASS.Agent_20240308.log)
[[2024-03-07] HASS.Agent_20240308.log](https://github.com/hass-agent/HASS.Agent/files/14667614/2024-03-07.HASS.Agent_20240308.log)
[[2024-03-08] HASS.Agent_restart_20240308.log](https://github.com/hass-agent/HASS.Agent/files/14667615/2024-03-08.HASS.Agent_restart_20240308.log)
[[2024-03-08][E] HASS.Agent_servicestop_20240308.log](https://github.com/hass-agent/HASS.Agent/files/14667616/2024-03-08.E.HASS.Agent_servicestop_20240308.log)
[[2024-03-08][E] HASS.Agent_servicereinstall_20240308.log](https://github.com/hass-agent/HASS.Agent/files/14667617/2024-03-08.E.HASS.Agent_servicereinstall_20240308.log)
[[2024-03-07] HASS.Agent_20240307.log](https://github.com/hass-agent/HASS.Agent/files/14667618/2024-03-07.HASS.Agent_20240307.log)
[[2024-03-07] HASS.Agent_restart_20240307.log](https://github.com/hass-agent/HASS.Agent/files/14667619/2024-03-07.HASS.Agent_restart_20240307.log)
[[2024-03-07][E] HASS.Agent_compatmigrate_20240307.log](https://github.com/hass-agent/HASS.Agent/files/14667620/2024-03-07.E.HASS.Agent_compatmigrate_20240307.log)
[[2024-03-20] HASS.Agent_restart_20240320.log](https://github.com/hass-agent/HASS.Agent/files/14667621/2024-03-20.HASS.Agent_restart_20240320.log)
[[2024-03-13] HASS.Agent_20240320.log](https://github.com/hass-agent/HASS.Agent/files/14667622/2024-03-13.HASS.Agent_20240320.log)
[[2024-03-13] HASS.Agent_20240318.log](https://github.com/hass-agent/HASS.Agent/files/14667623/2024-03-13.HASS.Agent_20240318.log)
[[2024-03-13] HASS.Agent_20240313.log](https://github.com/hass-agent/HASS.Agent/files/14667624/2024-03-13.HASS.Agent_20240313.log)
[[2024-03-11] HASS.Agent_20240313.log](https://github.com/hass-agent/HASS.Agent/files/14667625/2024-03-11.HASS.Agent_20240313.log)

**Comment by amadeo-alex** [comment]
All leads are tracing back to audio sensor/commands - more information will follow.

**Comment by amadeo-alex** [comment]
As per discord conversation, test build with AudioSwitcher instead of CoreAudio library - https://github.com/amadeo-alex/HASS.Agent/releases/tag/2.0.1-alpha-audioleakfix
Another test build will be created according to advice from CoreAudio author to try to keep the usage for CoreAudio for audio sensors and commands - https://github.com/morphx666/CoreAudio/issues/27

**Comment by amadeo-alex** [comment]
Update: CSCore was chosen as a audio information library with DIY solution for activating the devices.
