### ISSUE TITLE
Bug: "Key" Command Not Working In Retroarch

### ISSUE THREAD

**Issue by royaltongue** [hass-agent/HASS.Agent#65]
**Describe the bug**
I have set up a command to show a button that triggers pressing the "R" button on my keyboard. This works normally in text fields like in the URL bar in my browser or in Notepad, but doesn't seem to be working in Retroarch. In Retroarch's keybind settings, the keypress isn't registered at all.

**To Reproduce**
1. Create a Key Command
2. Try to use said Key Command in Retroarch (while trying to bind)

**Expected behavior**
I expect the keypress to be registered

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://github.com/hass-agent/HASS.Agent/assets/61848270/a081f9cb-ba42-4a67-ba80-d730f340068d)

 - Windows' UI language:  English
 
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`.

[[2024-04-02] HASS.Agent_20240402.log](https://github.com/hass-agent/HASS.Agent/files/14845394/2024-04-02.HASS.Agent_20240402.log)

**Comment by amadeo-alex** [comment]
Interesting, seems more like an Retroarch quirk than HASS.Agent itself - have you notices such behaviour anywhere else?
In the background HASS.Agent is using two different methods for simulating key press:
- WinForms "SendKeys" for "MultipleKeysCommand"
- user32.dll "SendInput" for "KeyCommand"

Could you please try the same with "MultipleKeysCommand"? Of course configured only to send "R".
If it works we may think about replacing user32.dll calls with "SendKeys".

PS: +1 for the license owner name :D

**Comment by royaltongue** [comment]
Just tested it, Multiple Keys behaves the same way

**Comment by amadeo-alex** [comment]
That's what I was afraid of. I wonder what retroarch is doing dofferently that it's not receiving the key input events.
Are you aware of any other application that can succesfully emulate keypress for retroarch?

**Comment by royaltongue** [comment]
I tried sending the hotkey with AutoHotKey but wasn't able to get it working. I tried using SendInput, SendPlay, and SendEvent

I tried sending the hotkey with AutoHotKey's `SendInput`, `SendPlay`, and `SendEvent` commands, but ran into the same issue. The keystroke is picked up by any old keyboard tester but Reotrarch refuses to do anything

**Comment by royaltongue** [comment]
Just tested a macro simulator called SuperMacro through the Stream Deck software and it also has the same problem. Guess I'll have to bring this up with the retroarch devs somewhere...

**Comment by lsaranto** [comment]
I've been told that some programs (often games) don't scan the keyboard buffer often enough. The simulated keypress is so fast that the program doesn't catch it. Splitting the keyPress command to separate keyDown and keyUp commands may help. You can also try adding a short delay between the keyDown and keyUp commands (ex. 40-50 ms).
