### ISSUE TITLE
Feature: allow user to set up `device_class` and `unit_of_measurement` values for the entities that are created for WMI-based sensors

### ISSUE THREAD

**Issue by spikeygg** [hass-agent/HASS.Agent#66]
**Is your feature request related to a problem? Please describe.**
I was playing around with sending WMI values and I noticed that the entities created are all raw, string-based, entities. If the entities are not customized on the Home Assistant side, the result is poor history and no units for the entity. Here's an example of one I created to measure CPU temperature:
![image](https://github.com/hass-agent/HASS.Agent/assets/1015891/02497216-a69e-47fa-94f3-395560a9583c)
The value 38 has no units and is in fact a string which cannot yield a nice numerical graph.

**Describe the solution you'd like**
On the configuration of the WMI details, include a way to describe the `device_class` and `unit_of_measurement` values which will be sent to Home Assistant when the entity is created. This would streamline the creation of all entities and make them more definable directly from the client.

**Describe alternatives you've considered**
The current method for setting this up is to use a workaround by configuring the `customization.yaml` and adding more detail about each sensor from the Home Assistant side which works but with this solution, everything is configured from the client-side and no server-side configuration is needed (encapsulation).

**Additional context**
None

**Comment by amadeo-alex** [comment]
Doable I think :)

**Comment by acshef** [comment]
I think `state_class` should be included in this too!

**Comment by amadeo-alex** [comment]
Done in https://github.com/amadeo-alex/HASS.Agent/tree/feature-wmi-advancedsettings - should be merged into organisation's 2.1.0-beta2 branch in a day or so.
