### ISSUE TITLE
Bug: Device name doesn't update in Home Assistant

### ISSUE THREAD

**Issue by Mystically11** [hass-agent/HASS.Agent#68]
Please make sure that the issue you're planning to report is not already registered :)

----

**Describe the bug**
After setting a new device name in the HASS.Agent application, the Home Assistant integration fails to recognize it and keeps discovering the old one, in which no functions work as the names don't match between the client and HA.

MQTT broker updates correctly, in MQTT Explorer under hass.agent/devices, both the old and new name show up.

**To Reproduce**
1. Go to Configuration > General in HASS.Agent
2. Change device name to something else and save
3. Remove old name entry from the HASS.Agent Home Assistant Integration and restart
4. In the "Discovered" tab, the old device name will show up.

**Expected behavior**

**Screenshots**

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
 - Windows' UI language: 
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [ ] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`.

**Comment by amadeo-alex** [comment]
Thank you very much for detailed information!
Part of the issue is that the "HASS.Agent Integration" requires HA restart to refresh (but that's something we need to fix separately @DrR0X-glitch) but anther half is issue of "device discovery messages" not being cleared after name change.
I'll create a PR with fix for the 2.0.1-beta2.

**Comment by amadeo-alex** [comment]
Reopened until 2.1.0-beta2 is released for clarity sake.
