### ISSUE TITLE
Feature: Process name as attribute of Active Window

### ISSUE THREAD

**Issue by barrelltitor** [hass-agent/HASS.Agent#73]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the process name of the current active window for use in other automations, such as dynamically changing the volume of the current active process, killing the active window in case it's frozen and I can't get out, and others

**Describe the solution you'd like**
The process name in an attribute. For example, for "Call of Duty 2" it should show "CoD2SP_s" in the attribute

**Describe alternatives you've considered**

**Additional context**

**Comment by amadeo-alex** [comment]
In progress :)
