### ISSUE TITLE
Bug: Screenshot Sensor incorrect handling of 21:9 Ratio

### ISSUE THREAD

**Issue by ElDingo424** [hass-agent/HASS.Agent#81]
**Describe the bug**
Screenshot sensor does not properly capture 21:9 Aspect Ratio, clips off right side.

**To Reproduce**
-21:9 aspect ratio
-Observe screenshot received in dashboard

**Expected behavior**
Full screen should be captured and displayed.

**Screenshots**
![image](https://github.com/hass-agent/HASS.Agent/assets/55253365/02ce6964-078d-4c1c-862a-ff09044cdfc7)
Image from screenshot sensor - 2 application windows set to half screen for reference.

![image](https://github.com/hass-agent/HASS.Agent/assets/55253365/b316b935-ff98-4be0-a6ab-151b2c5b05b1)
Expected image.

**Misc info:**
 - Windows build: 
![image](https://github.com/hass-agent/HASS.Agent/assets/55253365/c22977ff-97fc-4df3-bb2b-8c4d645ebdd5)

 - Windows' UI language: English
 - HASS.Agent version: Beta 2.1.0

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
Currently screen is at 125% scaling, changing to 100% scaling has no observable affect.
Resolution is 3440x1440

**Comment by amadeo-alex** [comment]
Now if I only had a ultra wide monitor :D
I'll take a look if I can find a "dry" solution to this and then supply you with a custom build that can be tested - if you'd be up to it of course.

**Comment by amadeo-alex** [comment]
Hmm, looks like there is more depth to it, even setting one of my screens to 150% scaling causes the image to have more or less only the top left quarter.

**Comment by ElDingo424** [comment]
I would be willing to test whatever you like, just let me know. (and have some grace as I'm somewhat new to all this)

**Comment by amadeo-alex** [comment]
Here you go: https://github.com/amadeo-alex/HASS.Agent/releases/tag/2.1.0-beta2-screenshot-scaling (note that it's from my repository where dev work happens)

This is also mentioned under the link but the fix attempt was done based on 2.1.0-beta2 branch so it also includes other changes.

**Comment by ElDingo424** [comment]
It looks like the screen does capture properly in this new version.

![image](https://github.com/hass-agent/HASS.Agent/assets/55253365/b20ceee9-012e-4cc3-b940-5ce49cdc537d)
Is there any other details you need?

**Comment by amadeo-alex** [comment]
If it is working as expected then excellent :)
I'll clean up the code and make it part of the official 2.0.1-beta2 release.
