### ISSUE TITLE
Bug: Crash when switching main displays in Windows 11

### ISSUE THREAD

**Issue by wynandtredoux** [hass-agent/HASS.Agent#94]
**Describe the bug**
On a system with more than 1 monitor, switching which monitor is the primary monitor causes a crash. Happens consistently. Error I'm seeing in the log is "[FTL] [MAIN] ThreadException: Specified cast is not valid."

**To Reproduce**
1. Start HASS.Agent
2. Right click on desktop -> Display settings
3. Click on a display that is currently not the main display
4. Check "Make this my main display" box
5. After a few seconds, HASS.Agent will crash

**Expected behavior**
HASS.Agent should not crash

**Screenshots**
![Screenshot 2024-05-19 185806](https://github.com/hass-agent/HASS.Agent/assets/23250202/f525cd6a-7212-4d9b-a9b0-b2d4ca0d238d)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 

![Screenshot 2024-05-19 190053](https://github.com/hass-agent/HASS.Agent/assets/23250202/e4bdecba-185e-4d02-9325-cd08a9868ca5)

 - Windows' UI language: English
 - HASS.Agent version: 2.0.1

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**
I usually switch displays by running "nircmd.exe setprimarydisplay" via a hotkey. But changing the setting through the Windows settings menu produces the same result. Use-case for me is to switch the primary display to a TV for Steam's "Big Picture" mode. 

**Logs**
Attaching logs with "Extended Logging" enabled. 
[[2024-05-19] HASS.Agent_20240519_crash.log](https://github.com/hass-agent/HASS.Agent/files/15371784/2024-05-19.HASS.Agent_20240519_crash.log)

**Comment by amadeo-alex** [comment]
Hello, can you please try https://github.com/hass-agent/HASS.Agent/releases/tag/2.1.0-beta1 ?

**Comment by wynandtredoux** [comment]
Ah, I should've checked the beta changelog. Looks to be working fine with 2.1.0-beta1
