### ISSUE TITLE
Bug: sensor.microphoneprocess Updates sensor incorrectly

### ISSUE THREAD

**Issue by jsp196** [hass-agent/HASS.Agent#99]
**Describe the bug**
When using the sensor.microphoneprocess sensor in Hass.Agent, the entity in HA properly updates the main value (the number of devices using the microphone) and adds an attribute in the form of `application using mic: "on"`.  After the microphone is no longer in use, it properly updates the main attribute (number of devices using the microphone) but does not update the additional attribute either by removing it or changing it to "off".  

Also I believe this is a different functionality than the original Hass.Agent which just set the name of the main attribute to the name of the process using the microphone.  I can work around this in my automation though.

**To Reproduce**
Enable the HASS Agent integration.
Check the attributes.
Use the microphone on a computer.  Then turn it off.
Check the attributes and notice that the application that was using the microphone is still listed as "on" even after the update threshold.

**Expected behavior**
Should either change to the application name with "off" listed or it should go away.  A better implementation would be to have the attribute be standard "application" and then the value be the name of the application.

**Misc info (please complete the following information):**
 - HASS.Agent version: 2.1.0-beta1
 - HA version 2024.5

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service
 - [x] Problem occurs in Home assistant

![ha-github](https://github.com/hass-agent/HASS.Agent/assets/30936755/f9236949-b62d-4c29-ad7d-0c9b05ee9229)

**Comment by amadeo-alex** [comment]
Hello, thanks for reporting, most likely fixed with https://github.com/hass-agent/HASS.Agent/pull/76 - will be part of 2.1.0 :)

**Comment by 1liminal1** [comment]
Did this ever go in? Im getting the same behavior still? Just a number, not process name.

**Comment by amadeo-alex** [comment]
> Did this ever go in? Im getting the same behavior still? Just a number, not process name.

It is in the beta releases of 2.1.0 (available on the releases page). 2.1.0 should be out next week or the one after :)

**Comment by 1liminal1** [comment]
Awesome, thank you :)

**Comment by 1liminal1** [comment]
I just updated to 2.1.0 and it still just shows a 1 rather then a process name. What can I check here?

**Comment by amadeo-alex** [comment]
The sensor will show a numeric value with number of programs using the microphone.
Specific names of those can be found in the attributes:
![8RQjyo](https://github.com/user-attachments/assets/42052156-7654-4c15-8e4f-63a7c860e4b5)
